group=org.evlis.aincrad
version=1.21.11-R0.1-SNAPSHOT
mcVersion=1.21.11
# base26 version string, increment by letter
acVersion=ABO
apiVersion=1.21.11

# Paper upstream commit
paperCommit=c5eb0790f199da6c38d0a650e1e5cd5415b28185

# Set to true while updating Minecraft version
updatingMinecraft=false
updateTaskListIssue=https://github.com/PaperMC/Paper/issues/11736

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
